### ISSUE TITLE
SSM WriteTo HandleMsg error: EOF

### ISSUE THREAD

**Issue by infinitydon** [surajincloud/kubectl-eks#4]
Hi, I tried to use SSM but getting the following error in the output

```
root@9c6c01f9d853:/tmp# kubectl eks ssm ip-172-30-233-238.ec2.internal
SSM into node i-0670318xxxx
2023/01/10 15:41:32 WriteTo HandleMsg error: EOF
2023/01/10 15:41:32 <nil>
root@9c6c01f9d853:/tmp#
```

Normal SSM into the same node works

**Comment by surajnarwade** [comment]
Hi @infinitydon thanks for reporting the issue. I faced the same with some of my nodes as well. I will roll out the patch soon.

**Comment by infinitydon** [comment]
Now am getting the following error about glibc

```
root@9c6c01f9d853:/# /tmp/kubectl-eks -h
/tmp/kubectl-eks: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/kubectl-eks)
/tmp/kubectl-eks: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/kubectl-eks)
```

**Comment by surajnarwade** [comment]
what operating system and arch are you on ?
I tested it on linux amd64 and it is working for me.

**Comment by infinitydon** [comment]
Tested on Ubuntu focal and Amazon Linux 2

**Comment by surajnarwade** [comment]
interesting, maybe your OS don't have those libraries and might need update.
I tried it on fedora and macOS, it worked though.

**Comment by infinitydon** [comment]
I think this should not be, all the k8s binaries are not selective to the OS version..

But I tried with ubuntu jammy now, still encountering the same error

```
root@11f3e6f38b5e:/# kubectl eks ssm ip-172-30-225-103.ec2.internal
SSM into node i-05dc47503988797bf
2023/02/17 18:01:07 WriteTo HandleMsg error: EOF
2023/02/17 18:01:07 <nil>
```

Also the version is still showing 0.0.1

```
root@11f3e6f38b5e:/tmp# tar -xzf kubectl-eks_0.1.1_linux_amd64.tar.gz
root@11f3e6f38b5e:/tmp#
root@11f3e6f38b5e:/tmp#
root@11f3e6f38b5e:/tmp# ./kubectl-eks version
v0.0.1
```

**Comment by infinitydon** [comment]
Tried to build directly from source:

```
root@11f3e6f38b5e:~/kubectl-eks# kubectl eks ssm ip-172-30-225-103.ec2.internal
SSM into nodei-05dc4xxxxxxx in region us-east-1

----------ERROR-------
Encountered error while initiating handshake.  failed on client with status 0 error: 2023/02/17 18:19:30 ReadFrom write error: buffer full
2023/02/17 18:19:30 buffer full
root@11f3e6f38b5e:~/kubectl-eks#
root@11f3e6f38b5e:~/kubectl-eks#
```

One thing about my env is that SSM is secured using KMS, I don't know if that could be an issue.

```
root@11f3e6f38b5e:~/kubectl-eks# aws ssm start-session --target i-05dc4xxxxxxx

Starting session with SessionId: xxxxxxx@-0095ddxxxxxx
This session is encrypted using AWS KMS.
/bin/bash
cd /home/ssm-user/
clear
sh-4.2$ /bin/bash
```

**Comment by surajnarwade** [comment]
@infinitydon I think KMS is the issue here, let me test it out with KMS and get back to you

**Comment by surajnarwade** [comment]
@infinitydon can you test out this PR: https://github.com/surajincloud/kubectl-eks/pull/7 if possible.
Currently I don't have SSM with KMS encryption, but it would be really helpful if you test it out :) 
Let me how it goes, thank you so much 🙏

**Comment by surajnarwade** [comment]
@infinitydon I managed to test out with new changes, and it is working 🎉

**Comment by infinitydon** [comment]
Confirmed.. Much thanks..
